services:
  postgres:
    image: postgres:16-alpine
    container_name: placas-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: placas
    ports:
      - '5432:5432'
    volumes:
      - placas_pg:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U app -d placas']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: placas-redis
    ports:
      - '6379:6379'
    volumes:
      - placas_redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  placas_pg:
  placas_redis:
